# basic options
title: Tom de Roos | Front-end developer
author: Tom de Roos
email: tomderoos@gmail.com
description: A personal portfolio website for myself.
twitter_username: tomderoos

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
